---
# Variables that can provide as extra vars
#VPC_NAME: test
#VPC_REGION: eu-west-1 # N.Virginia
#EC2_INSTANCE_TYPE: t2.micro
EC2_KEY_NAME: "my-default-key"
#EC2_SECURITY_GROUP_NAME: "test"
EC2_COUNT_DOCKER: 1
EC2_VOLUME_SIZE_DOCKER: 100
#EC2_SUBNET_ID: []
# Example of EC2_SUBNET_ID
# EC2_SUBNET_ID:
#   - "subnet-0c3e0b7b"
#   - "subnet-bf672ae6"
#AMI_NAME: ""
#AMI_OWNER: ""

# Tags
#ENVIRONMENT: test
#SERVER_ROLE: test

# Use inside the tasks
vpc_name: "{{ VPC_NAME }}"
vpc_region: "{{ VPC_REGION }}"
ec2_instance_type: "{{ EC2_INSTANCE_TYPE }}"
ec2_key_name: "{{ EC2_KEY_NAME }}"
ec2_security_group_name: "{{ EC2_SECURITY_GROUP_NAME_DOCKER }}"
ec2_volume_size: "{{ EC2_VOLUME_SIZE_DOCKER }}"
ec2_count: "{{ EC2_COUNT_DOCKER }}"
ec2_subnet_id: "{{ EC2_SUBNET_ID_DOCKER }}"

# Please don't change the variables below, until you know what you are doing
# Only Ubuntu distribution is supported
  
ami_id: "{{ AMI_ID }}"
ami_owner: "{{ AMI_OWNER }}"
